[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite builds to 'dist' by default)
  publish = "dist"
  
  # Node.js version
  environment = { NODE_VERSION = "20" }

[build.processing]
  # Skip processing of images, CSS, and JS (Vite already optimizes these)
  skip_processing = false

[build.processing.css]
  # Let Vite handle CSS optimization
  bundle = false
  minify = false

[build.processing.js]
  # Let Vite handle JS optimization  
  bundle = false
  minify = false

[build.processing.html]
  # Let Vite handle HTML optimization
  pretty_urls = true

# SPA (Single Page Application) redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

# Cache static assets for longer
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML files for shorter time
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Cache CSS and JS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Preload critical resources
[[headers]]
  for = "/index.html"
  [headers.values]
    Link = "</assets/index.css>; rel=preload; as=style, </assets/index.js>; rel=preload; as=script"

# Development settings (for Netlify Dev)
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  autoLaunch = false

# Functions settings (if you add serverless functions later)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Form handling (if you add contact forms later)
[forms]
  # Enable form detection
  # Forms will be automatically detected in your HTML 