[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Node.js version
  environment = { NODE_VERSION = "20" }

# Netlify Next.js plugin for API routes support
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  # Let Next.js handle optimization for static export
  skip_processing = false

[build.processing.css]
  # Let Next.js handle CSS optimization
  bundle = false
  minify = false

[build.processing.js]
  # Let Next.js handle JS optimization  
  bundle = false
  minify = false

[build.processing.html]
  # Let Next.js handle HTML optimization
  pretty_urls = true

# Next.js redirects handled by the plugin

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

# Cache Next.js static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images and other static files
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Development settings (for Netlify Dev)
[dev]
  command = "npm run dev"
  port = 3000
  autoLaunch = false

# Functions settings (if you add serverless functions later)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Form handling (if you add contact forms later)
[forms]
  # Enable form detection
  # Forms will be automatically detected in your HTML 